config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
    resources :comments
    member do
      # Adds two routes, one for upvoting and another for downvoting that will update current like and dislikes size in votes table.
      # like_pin     PUT    /pins/:id/like(.:format)       pins#upvote
      # dislike_pin  PUT    /pins/:id/dislike(.:format)    pins#downvote
      put "like", to: "pins#upvote"
      put "dislike", to: "pins#downvote"
    end
  end
  # Uses same name route as the tag
  get 'tags/:tag', to: 'pins#tagged', as: :tag
  root 'pins#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :pin
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  # Votable
  acts_as_votable
    # upvote_by ..... => Add upvote by current_user
    # get_dislikes.size => Count all downvotes
    # get_likes.size => Count all upvotes

  # Taggable
  acts_as_taggable_on :tags

  # Friendly Id
  extend FriendlyId
  friendly_id :title, use: :slugged

  # Imagemagick
  has_attached_file :image, styles: {medium: "300x300>"}
  # Makes sure it is an actual image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  @comment = Comment.new(comment_params)
    @comment.pin_id = params[:pin_id]
    @comment.save
    redirect_to pin_path(@comment.pin)
  end

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all.order("created_at DESC")
    @tags = Pin.tag_counts_on(:tags)
  end

  def show
    @pin = Pin.friendly.find params[:id]
    @comment = Comment.new
    @comment.pin_id = @pin.id
  end

  def new
    # Builds pin from the current user, so when a user makes a pin, the pin will have its user_id automatically
    @pin = current_user.pins.build
  end

  def create
    @pin = current_user.pins.build pin_params
    if @pin.save
      flash.notice = "New Pin, #{@pin.title}, Created!"
      redirect_to @pin
    else
      render new_pin_path
    end
  end

  def edit
    @pin = Pin.friendly.find params[:id]
  end

  def update
    @pin = Pin.friendly.find params[:id]
    if @pin.update pin_params
      flash.notice = "#{@pin.title} Updated!"
      redirect_to @pin
    else
      render edit_pin_path
    end
  end

  def destroy
    @pin = Pin.friendly.find params[:id]
    @pin.destroy
    flash.notice = "#{@pin.title} Deleted!"
    redirect_to root_path
  end

  def upvote
    @pin = Pin.friendly.find params[:id]
    # We get .upvote_by because we added acts_as_votable to pin model
    @pin.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @pin = Pin.friendly.find params[:id]
    @pin.downvote_by current_user
    redirect_to :back
  end

  def tagged
    # Tag_list returns an array of tags
    if params[:tag].present?
      @pins = Pin.tagged_with(params[:tag])
    else
      @pins = Pin.all.order("created_at DESC")
    end
  end

  private

  def pin_params
    params.require(:pin).permit(:title, :description, :image, :tag_list, :slug)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
  # Generates a tag cloud
  include ActsAsTaggableOn::TagsHelper
end

app/views/comments/_form.html.haml
.col-md-6.col-md-offset-3.comment-form
  = form_for [@pin, @comment] do |f|
    .form-group
      = f.label :author_name, "Your Name"
      = f.text_field :author_name, {class: 'form-control'}

    .form-group
      = f.label :body
      = f.text_area :body, {class: 'form-control'}

    = f.submit class: "btn btn-primary pull-right"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Not Pinterest
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-fixed-top
      -# Turn any fixed-width grid layout into a full-width layout by changing your outermost with container or container-fluid
      .container
        .navbar-brand= link_to "Not Pinterest", root_path
        - if user_signed_in?
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "New Pin", new_pin_path
            %li= link_to "My Account", edit_user_registration_path
            %li= link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Sign Up", new_user_registration_path
            %li= link_to "Sign In", new_user_session_path
    .container
      - flash.each do |message_type, message|
        = content_tag :div, message, class: "alert alert-info"
      = yield

app/views/pins/_comment.html.haml
.col-md-6.col-md-offset-3
  .panel.panel-default.comments
    .panel-heading
      %h5
      Comment by
      = comment.author_name
      %h6.pull-right= distance_of_time_in_words(comment.pin.created_at, comment.created_at)
    .panel-body
      %p= comment.body

app/views/pins/_form.html.haml
= form_for @pin, html: { multipart: true} do |f|
  - if @pin.errors.any?
    #errors
      %h2
      = pluralize(@pin.errors.count, "error")
      Pin Did Not Save
      %ul
        - @pin.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :title
    = f.text_field :title, {class: 'form-control'}

  .form-group
    = f.label :description
    = f.text_area :description, {class: 'form-control'}

  .form-group
    = f.label :tag_list, "Tags (Separate By Commas)"
    = f.text_field :tag_list, {class: 'form-control'}

  .form-group
    = f.label :image, "Upload New Image"
    = f.file_field :image, {class: 'form-control'}

  = f.submit class: "btn btn-primary"

app/views/pins/edit.html.haml
-# Offset increase the left margin of a column by * columns
.col-md-6.col-md-offset-3
  %h1 Edit Pin
  = image_tag @pin.image.url(:medium)
  = render 'form'
  %br
  = link_to "Cancel", @pin, :class =>  "btn btn-danger"

app/views/pins/index.html.haml
#pins.transitions-enabled
  - @pins.each do |pin|
    .box.panel.panel-default
      -# link_to image_tag imageLocation, link you want to go to when clicked
      = link_to (image_tag pin.image.url), pin
      .panel-body
        %h2= link_to pin.title, pin
        %hr
        %p= pin.description
        %hr
        %p
        Pinned by
        = pin.user.email

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
  %h1 New Form
  = render 'form'
  %br
  = link_to "Cancel", root_path, :class => "btn btn-danger"

app/views/pins/show.html.haml
#pin.row
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading.pin-image
        = image_tag @pin.image.url
      .panel-body
        %h2= @pin.title
        %p= @pin.description
      .panel-footer
        .row
          .col-md-6
            %p
            Tags:
            - if @pin.tags.any?
              - @pin.tags.each do |tag|
                = link_to tag.name, tag_path(:tag => tag.name)
        %hr
        .row
          .col-md-6
            %p
            Pinned by
            = @pin.user.email
          .col-md-6
            .btn-group.pull-right
              -# = link_to "upvote", like_link_path(link), method: :put
              = link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do
                %span.glyphicon.glyphicon-arrow-up
                  = @pin.get_upvotes.size
              = link_to dislike_pin_path(@pin), method: :put, class: "btn btn-default" do
                %span.glyphicon.glyphicon-arrow-down
                  = @pin.get_downvotes.size
              -# = @pin.get_upvotes.size - @pin.get_downvotes.size
              -# <%= link_to "Back", root_path %>
              - if user_signed_in?
                = link_to "Edit", edit_pin_path, class: "btn btn-default"
                = link_to "Delete", pin_path, class: "btn btn-default", method: :delete, data: {confirm: "Do you really want to delete this pin?"}
= render partial: 'comments/form'
= render partial: 'pins/comment', collection: @pin.comments

app/views/pins/tagged.html.haml
#pins.transitions-enabled
  - @pins.each do |pin|
    .box.panel.panel-default
      -# link_to image_tag imageLocation, link you want to go to when clicked
      = link_to (image_tag pin.image.url), pin
      .panel-body
        %h2= link_to pin.title, pin
        %hr
        %p= pin.description
        %hr
        %p
        Pinned by
        = pin.user.email